name: URL Check

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check URLs
        uses: paramt/url-checker@master
        with:
          files: "Academic and Grey Literature Research Tools.md, Academic.md, Acronyms and Abbreviations.md, Adderall.md, Ancestry Research.md, Annotation and Highlighting.md, Apps.md, Audio Books.md, Awesome Design Tools.md, Awesome Internet Finds.md, BOOKMRKS-MTHRFCKR-02.md, BOOKMRKS-MTHRFCKR.md, Browser Related.md, Communities.md, Content Blogs, RSS and Feeds.md, Content.md, Data Integration and Visualisers.md, Design.md, Development.md, DevOps.md, DocArticles.md, Document Checking.md, Downloads.md, Ebooks.md, EDU.md, Financial.md, Git.md, Glossaries and Dictionaries.md, Google.md, GrammerSpellingEtc.md, Journal.md, Learning.md, Links from WebOasis.md, Memex.md, Music DL.md, Music.md, Newspaper Sites.md, Notetaking.md, Obsidian.md, OSINT and Hacking.md, OSINT SEARCH ENGINES.md, OSINT.md, Papers and Journals.md, PDF Management.md, PDF Sites.md, PKMS.md, Private Generator Tracker.md, Pro Audio.md, Programming.md, Projects.md, Publications.md, Raindrops.md, Reference Tools.md, Reference.md, Resources.md, Search Engines.md, Social media and photos.md, Social Media.md, Technology.md,The World Wide Web.md, Tools.md, UI Graphics.md, WebDev.md, YouTube Video  Audio Downloaders.md"
